### ISSUE TITLE
Unable to locate package ros-hydro-eband-local-planner

### ISSUE THREAD

**Issue by aba92** [vislab-tecnico-lisboa/vizzy-simulator#2]
Hi!
When trying to install the eband-local-planner, i get the error:
Unable to locate package ros-hydro-eband-local-planner.
Where else i can find that package, i tried to search but with no success.
Thanks

**Comment by mikearagao** [comment]
Hey @aba92!

What version of ROS are you using? Sure it is the hydro version?

We are currently working on a major update for all of Vizzy's repositories (vizzy-yarp, vizzy-simulator, vizzy-description and vizzy-navigation) and there are still a lot of untested launches... I guess you'll find a lot of errors trying to run the robot on simulation :disappointed: 

We hope to have a working version next week!

Do you need the simulator for some urgent goal? Or is it just for curiosity purposes?

Cheers!

**Comment by aba92** [comment]
Actually i'm a IST student and i'm starting a project that needs those libraries. And yes, i'm using the ROS Indigo. Should I wait for next week or install ROS hydro?

**Comment by plinioMoreno** [comment]
Hi @aba92, I guess you only need the mobile platform, don't you? I think @mikearagao is working on the arms and the head, and not the ROS Indigo right now.

@mikearagao managed to set it up on Indigo, but the instructions are not online. So @mikearagao can tell you how he set it up, and if you just need the mobile platform, I guess you can go ahead.

Do you confim this, @mikearagao ?

**Comment by mikearagao** [comment]
@aba92 @plinioMoreno the mobile base should work in theory but I guess it won't work by just using the launch files without changes... Of course you can look at the errors and try to comment the issuing lines!

About the ROS Indigo there is still a problem because the planner that we use with Vizzy has no support for this version yet. You can try to find another planner (feel free to propose a new one) or you can go back to ROS Hydro (in this case you'll probably need to downgrade your Ubuntu version to 12.04).

**Comment by aba92** [comment]
Ok thanks to everyone. I'll downgrade do Ubuntu 12.04 and install the Hydro Version.

**Comment by aba92** [comment]
Hi!
Now I could install all libraries without any error. Everything look's fine and let me say that your work is amazing. Now it's time to play with it ....
Thanks for your help

**Comment by mikearagao** [comment]
Hi! Thank you! But are you still using this repository? Please use the new one www.github.com/vislab-tecnico-lisboa/vizzy

**Comment by aba92** [comment]
yes, i'm using that one, in ubuntu 12.04 and ros hydro.

**Comment by ruipimentelfigueiredo** [comment]
Hi! To install the missing dependencies, try this:

rosdep install vizzy_description vizzy_control vizzy_gazebo vizzy_launch
vizzy_sensors vizzy_navigation

**Comment by mikearagao** [comment]
He had already solved that...

**Comment by aba92** [comment]
Can anyone tell me if i should install OpenCV to use vizzy's cameras (both in simulation and real)?

**Comment by mikearagao** [comment]
Moving this issue to here: https://github.com/vislab-tecnico-lisboa/vizzy/issues/38
